# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PC.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Interface import Interface

class Menu_PC(Interface):
    def __init__(self, MainWindow):
        super().__init__(MainWindow)
        self.MenuEquipe = QtWidgets.QListWidget(MainWindow)
        self.MenuEquipe.setGeometry(QtCore.QRect(10, 10, 181, 471))
        self.MenuEquipe.setObjectName("MenuEquipe")
        self.MenuPC = QtWidgets.QListView(MainWindow)
        self.MenuPC.setGeometry(QtCore.QRect(320, 10, 171, 471))
        self.MenuPC.setObjectName("MenuPC")
        self.Ajouter = QtWidgets.QPushButton(MainWindow)
        self.Ajouter.setGeometry(QtCore.QRect(210, 170, 89, 25))
        self.Ajouter.setObjectName("Ajouter")
        self.Deposer = QtWidgets.QPushButton(MainWindow)
        self.Deposer.setGeometry(QtCore.QRect(210, 220, 89, 25))
        self.Deposer.setObjectName("Deposer")
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.Ajouter.clicked.connect(self.Ajout)
        self.Deposer.clicked.connect(self.Depot)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.Ajouter.setText(_translate("Form", "<- Ajouter"))
        self.Deposer.setText(_translate("Form", "Déposer ->"))
        
    def Ajout(self):
        pass
    
    def Depot(self):
        pass

    def hide(self):
        self.MenuEquipe.hide()
        self.MenuPC.hide()
        self.Ajouter.hide()
        self.Deposer.hide()
        
    def show(self):
        self.MenuEquipe.show()
        self.MenuPC.show()
        self.Ajouter.show()
        self.Deposer.show()